package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/basebandit/infragenie/internal/repo"
	"github.com/spf13/cobra"
)

func initCmd() *cobra.Command {
	var (
		starter string
		force   bool
	)

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Bootstrap a goldenpath.yml for the current repository",
		Long: `Inspect the current repository and generate a goldenpath.yml
tailored to the detected stack (language, platform, CI system).

Starter templates:
  platform-baseline   — root baseline for platform/SRE teams (default)
  kubernetes          — K8s microservices; extends platform-baseline
  fintech             — regulated/PCI environments; extends platform-baseline
  solo                — lightweight, standalone, low noise`,
		Example: `  infragenie init
  infragenie init --starter kubernetes
  infragenie init --starter fintech --force`,
		RunE: func(_ *cobra.Command, _ []string) error {
			out := "goldenpath.yml"
			if !force {
				if _, err := os.Stat(out); err == nil {
					return fmt.Errorf("%s already exists — use --force to overwrite", out)
				}
			}

			rc, _ := repo.Build(".")
			content := generate(starter, rc)

			if err := os.WriteFile(out, []byte(content), 0644); err != nil {
				return err
			}
			fmt.Printf("wrote %s\n", out)
			fmt.Println("next: infragenie review --goldenpath goldenpath.yml --diff HEAD~1")
			return nil
		},
	}

	cmd.Flags().StringVarP(&starter, "starter", "s", "platform-baseline",
		"starter template: platform-baseline, kubernetes, fintech, solo")
	cmd.Flags().BoolVar(&force, "force", false, "overwrite existing goldenpath.yml")
	return cmd
}

// generate builds goldenpath.yml content from the chosen starter, annotating
// detected stack entries so the user can see what was auto-detected.
func generate(starter string, rc *repo.Context) string {
	switch strings.ToLower(starter) {
	case "kubernetes", "k8s":
		return renderKubernetes(rc)
	case "fintech", "regulated":
		return renderFintech(rc)
	case "solo":
		return renderSolo(rc)
	default:
		return renderBaseline(rc)
	}
}

func renderBaseline(rc *repo.Context) string {
	return fmt.Sprintf(`# goldenpath.yml — generated by infragenie init
# Docs: https://github.com/basebandit/infragenie

version: 1
name: %s

stacks:
  runtimes: %s
  platforms: %s
  ci: %s

required_labels:
  - app.kubernetes.io/name
  - app.kubernetes.io/version
  - app.kubernetes.io/component
  - team

security:
  forbid_image_tag_latest: true
  require_non_root: true
  require_read_only_rootfs: true

observability:
  require_prometheus_annotations: true

ci_required_steps:
  - name: tests
    matches: %s
  - name: vulnerability-scan
    matches:
      - "aquasec/trivy"
      - "trivy image"
      - "grype"

runtime_rules:
  require-owner-annotation:
    pattern: "owner:"
    message: "manifest is missing an owner annotation"
    suggestion: "Add owner: <team-name> to metadata.annotations."

defaults:
  fail_on: high
  budget:
    tokens: 50000
    usd: 0.50

ignore:
  - path: examples/**
    rules: ["*"]
  - path: test/**
    rules: ["*"]
`, repoName(), yamlList(rc.Languages), yamlList(rc.Stacks), yamlList(rc.CISystems), testMatches(rc))
}

func renderKubernetes(rc *repo.Context) string {
	return fmt.Sprintf(`# goldenpath.yml — kubernetes workloads starter
# generated by infragenie init --starter kubernetes

version: 1
name: %s
extends: https://raw.githubusercontent.com/basebandit/infragenie/main/examples/golden-paths/platform-baseline.yml

stacks:
  runtimes: %s
  platforms:
    - kubernetes
    - helm
  ci: %s

required_labels:
  - app.kubernetes.io/name
  - app.kubernetes.io/version
  - app.kubernetes.io/component
  - team
  - cost-centre

chart_shape:
  charts_dir: charts
  required_files:
    - Chart.yaml
    - values.yaml

security:
  forbid_image_tag_latest: true
  require_non_root: true
  require_read_only_rootfs: true
  require_network_policy: true

observability:
  require_prometheus_annotations: true

ci_required_steps:
  - name: tests
    matches: %s
  - name: vulnerability-scan
    matches:
      - "aquasec/trivy"
      - "trivy image"
      - "grype"
  - name: helm-lint
    matches:
      - "helm lint"
      - "kubeconform"

runtime_rules:
  require-owner-annotation:
    pattern: "owner:"
    message: "manifest is missing an owner annotation"
    suggestion: "Add owner: <team-name> to metadata.annotations."

defaults:
  fail_on: high
  budget:
    tokens: 75000
    usd: 0.75

ignore:
  - path: examples/**
    rules: ["*"]
  - path: charts/legacy/**
    rules:
      - "goldenpath.security.require-read-only-rootfs"
`, repoName(), yamlList(rc.Languages), yamlList(rc.CISystems), testMatches(rc))
}

func renderFintech(rc *repo.Context) string {
	return fmt.Sprintf(`# goldenpath.yml — fintech / regulated starter
# generated by infragenie init --starter fintech

version: 1
name: %s
extends: https://raw.githubusercontent.com/basebandit/infragenie/main/examples/golden-paths/platform-baseline.yml

stacks:
  runtimes: %s
  platforms:
    - kubernetes
    - helm
  ci: %s

required_labels:
  - app.kubernetes.io/name
  - app.kubernetes.io/version
  - app.kubernetes.io/component
  - team
  - cost-centre
  - data-classification
  - compliance-scope

security:
  forbid_image_tag_latest: true
  require_non_root: true
  require_read_only_rootfs: true
  require_network_policy: true

observability:
  require_prometheus_annotations: true
  require_structured_logs: true

ci_required_steps:
  - name: tests
    matches: %s
  - name: sast
    matches:
      - "gosec"
      - "semgrep"
      - "codeql"
  - name: container-scan
    matches:
      - "aquasec/trivy"
      - "trivy image"
      - "grype"
  - name: dependency-scan
    matches:
      - "trivy fs"
      - "govulncheck"
      - "snyk test"
  - name: secret-scan
    matches:
      - "trufflehog"
      - "gitleaks"
      - "detect-secrets"

rules:
  goldenpath.security.require-network-policy:
    severity: critical
  goldenpath.security.no-latest-tag:
    severity: critical
  reliability.resource-limits:
    severity: critical

fail_on: high

defaults:
  budget:
    tokens: 100000
    usd: 1.00

ignore:
  - path: examples/**
    rules: ["*"]
  - path: test/**
    rules: ["*"]
`, repoName(), yamlList(rc.Languages), yamlList(rc.CISystems), testMatches(rc))
}

func renderSolo(rc *repo.Context) string {
	return fmt.Sprintf(`# goldenpath.yml — solo engineer starter
# generated by infragenie init --starter solo

version: 1
name: %s

stacks:
  runtimes: %s
  platforms: %s
  ci: %s

required_labels:
  - app
  - version

security:
  forbid_image_tag_latest: true

ci_required_steps:
  - name: tests
    matches: %s
  - name: container-scan
    matches:
      - "aquasec/trivy"
      - "trivy image"
      - "grype"

defaults:
  fail_on: high
  budget:
    tokens: 10000
    usd: 0.10
  reviewers:
    goldenpath: true
    reliability: true
    conventions: false

ignore:
  - path: examples/**
    rules: ["*"]
  - path: hack/**
    rules: ["*"]
`, repoName(), yamlList(rc.Languages), yamlList(rc.Stacks), yamlList(rc.CISystems), testMatches(rc))
}

// ── helpers ───────────────────────────────────────────────────────────────────

func repoName() string {
	cwd, err := os.Getwd()
	if err != nil {
		return "my-service"
	}
	return filepath.Base(cwd)
}

func yamlList(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	var b strings.Builder
	b.WriteString("\n")
	for _, item := range items {
		b.WriteString(fmt.Sprintf("    - %s\n", item))
	}
	return strings.TrimRight(b.String(), "\n")
}

func testMatches(rc *repo.Context) string {
	matchers := map[string]string{
		"go":     `"go test"`,
		"python": `"pytest"`,
		"node":   `"npm test"`,
		"rust":   `"cargo test"`,
		"java":   `"mvn test"`,
		"ruby":   `"rspec"`,
	}
	var matches []string
	for _, lang := range rc.Languages {
		if m, ok := matchers[lang]; ok {
			matches = append(matches, m)
		}
	}
	if len(matches) == 0 {
		matches = []string{`"go test"`, `"pytest"`, `"npm test"`}
	}
	var b strings.Builder
	b.WriteString("\n")
	for _, m := range matches {
		b.WriteString(fmt.Sprintf("      - %s\n", m))
	}
	return strings.TrimRight(b.String(), "\n")
}
